<a href="https://colab.research.google.com/github/glcn35/NUMPY/blob/main/Assignment_1_Student_(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [8]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [31]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [33]:
a=np.ones((4,4),dtype=int)
b=np.where(1,7,a)
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [34]:
c=np.where(1,7,a[2,2])
c

array(7)

In [24]:
#a.reshape((2,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

#### 6. Create same array above with full method

In [16]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [36]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [38]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [44]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [45]:
np.random.rand(5)

array([0.26996318, 0.66853716, 0.82250386, 0.91907731, 0.89048322])

#### 11. Create random normal distributed 5x5 array

In [46]:
np.random.rand(5,5)

array([[0.48526028, 0.22789941, 0.59128609, 0.14053431, 0.70460437],
       [0.72222095, 0.6967021 , 0.86024292, 0.31216133, 0.87702925],
       [0.21277448, 0.91783873, 0.71665573, 0.46507506, 0.06168304],
       [0.59727728, 0.60269335, 0.32855115, 0.89840978, 0.33015071],
       [0.14636629, 0.41150634, 0.24091438, 0.04723595, 0.11183426]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [48]:
np.random.randint(20,50,size=(3,4))

array([[25, 33, 41, 30],
       [43, 40, 48, 37],
       [47, 30, 31, 40]])

#### 13. Reshape the array below with shape 6x8

In [49]:
ranarr=[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]

In [51]:
ranarr= np.array(ranarr)
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [52]:
ranarr.reshape(6,8)
#np.array(ranarr).reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [58]:
#reshape with -1
ranarr.reshape(-1,12)  #(12,-1) de çalışır


array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [59]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [60]:
mat[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

In [69]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [64]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [67]:
mat[1,[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [79]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [107]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [96]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [111]:
#mat[[[1,1,3,3]],[[0,3,0,2]]]   bakacağız yapamadık array([[ 5, 77],[13, 77]])


array([[ 5,  8, 13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [112]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [127]:
a=mat[mat<10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [128]:
b=mat[mat>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [130]:
arr2=np.add(a,b)
arr2

array([78, 79, 81, 18, 20, 85, 25])

In [132]:
a+b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [117]:
np.std(arr2)

29.700546274093877

#### 22. Get the sum of second column from array above

In [134]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [133]:
np.sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [136]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [140]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [141]:
#median
np.median(mat[2])

10.5

In [142]:
#mean
np.mean(mat[2])

10.5

In [143]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [146]:
import pandas as pd

In [145]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [147]:
sal=pd.read_csv('/content/drive/MyDrive/Salaries.csv')

In [149]:
sal.head(5)
#sal.iloc[:5]

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [150]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [151]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [152]:
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [153]:
#max
max(sal.TotalPay)

567595.43

In [155]:
#avg
sal_avg=sal["TotalPay"].mean()
sal_avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [158]:
(sal.TotalPay>sal_avg).value_counts()  #eksik tamamlayalım where le çözülebilir mi?

False    79165
True     69489
Name: TotalPay, dtype: int64

**How much does ALBERT PARDINI make (including benefits)?**

In [161]:
sal["TotalPayBenefits"][2]  #İSTEDİĞİMİZ SÜTÜNDAKİ istediğimiz satır

335279.91

**Who is lowest paid person**

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [166]:
sal["EmployeeName"].iloc[sal.TotalPay.sort_values().head(11)]

148036    Carlos J Hernandez
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
0             NATHANIEL FORD
Name: EmployeeName, dtype: object

In [162]:
[sal.TotalPay.sort_values(ascending=False).tail(1)] 

[148653   -618.13
 Name: TotalPay, dtype: float64]

In [163]:
sal.TotalPay.sort_values().head(1)

148653   -618.13
Name: TotalPay, dtype: float64

**What are the unique Jobs in dataset?**

In [171]:
sal.JobTitle.sort_index().unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [172]:
sal.JobTitle.value_counts()

Transit Operator                                 7036
Special Nurse                                    4389
Registered Nurse                                 3736
Public Svc Aide-Public Works                     2518
Police Officer 3                                 2421
                                                 ... 
LEGISLATIVE ASSISTANT, CITY ATTORNEY'S OFFICE       1
Light Rail Vehicle Equip Eng                        1
CHIEF VICTIM/WITNESS INVESTIGATOR                   1
Cashier 3                                           1
LIEUTENANT I, (POLICE DEPARTMENT)                   1
Name: JobTitle, Length: 2159, dtype: int64

In [173]:
sal.JobTitle.value_counts(ascending=True).head(3)

LIEUTENANT I, (POLICE DEPARTMENT)    1
Cashier 3                            1
CHIEF VICTIM/WITNESS INVESTIGATOR    1
Name: JobTitle, dtype: int64

In [174]:
sal.JobTitle.value_counts().tail(3)

CHIEF VICTIM/WITNESS INVESTIGATOR    1
Cashier 3                            1
LIEUTENANT I, (POLICE DEPARTMENT)    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

20366

In [178]:
sal.groupby("Year").mean()["TotalPayBenefits"]

Year
2011     71744.103871
2012    100553.229232
2013    101440.519714
2014    100250.918884
Name: TotalPayBenefits, dtype: float64

In [179]:
sal[(sal["Year"]==2012)&(sal["TotalPayBenefits"]>93692.55481056834)].count()


Id                  20366
EmployeeName        20366
JobTitle            20366
BasePay             20366
OvertimePay         20366
OtherPay            20366
Benefits            20366
TotalPay            20366
TotalPayBenefits    20366
Year                20366
Notes                   0
Agency              20366
Status                  0
dtype: int64

In [175]:
sal["TotalPayBenefits"].mean()

93692.55481056834

In [176]:
sal.groupby(["Year"]).count()

Id  EmployeeName  JobTitle  ...  Notes  Agency  Status
Year                                 ...                       
2011  36159         36159     36159  ...      0   36159       0
2012  36766         36766     36766  ...      0   36766       0
2013  37606         37606     37606  ...      0   37606       0
2014  38123         38123     38123  ...      0   38123       0

[4 rows x 12 columns]

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here


4110

In [184]:
sal[sal["JobTitle"]=="Mobile Equipment Supervisor"]

Id   EmployeeName  ...         Agency  Status
57495  57496  Michael Handy  ...  San Francisco     NaN

[1 rows x 13 columns]

In [181]:
sal[sal["JobTitle"]=="GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY"]

Id    EmployeeName  ...         Agency  Status
0    1  NATHANIEL FORD  ...  San Francisco     NaN
83  84  EDWARD REISKIN  ...  San Francisco     NaN

[2 rows x 13 columns]

In [182]:
sal[sal["JobTitle"]=="MANAGER"]

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [185]:
sal_new=sal.drop(["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"], axis=1)
#sal.drop(columns = ["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"])
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [186]:
sal_new=sal_new.iloc[:,1:]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

In [187]:
sal_new.describe()

TotalPay  TotalPayBenefits
count  148654.000000     148654.000000
mean    74768.321972      93692.554811
std     50517.005274      62793.533483
min      -618.130000       -618.130000
25%     36168.995000      44065.650000
50%     71426.610000      92404.090000
75%    105839.135000     132876.450000
max    567595.430000     567595.430000

In [188]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]

EmployeeName  ... TotalPayBenefits
15847   TATYANA ROTENBERG  ...         74764.87
15848         WINSTON HOM  ...         74761.55
15849        CRAIG RIGLER  ...         74759.92
15850           WENDY TAN  ...         74756.76
15851      KENNETH BREWER  ...         74751.59
...                   ...  ...              ...
148648        Leon Walker  ...             0.00
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00

[79164 rows x 4 columns]