<a href="https://colab.research.google.com/github/glcn35/NUMPY/blob/main/Assignment_1_Student_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
np.ones((4,4), dtype=int).reshape

<function ndarray.reshape>

#### 5. Make all the values of the array above 7

#### 6. Create same array above with full method

In [5]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [6]:
np.arange(2,17,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [7]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [8]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [9]:
np.random.rand(5)

array([0.65549475, 0.46864432, 0.07072703, 0.73790181, 0.40283017])

#### 11. Create random normal distributed 5x5 array

In [10]:
np.random.rand(5,5)

array([[0.87135442, 0.20562428, 0.34760808, 0.56602898, 0.20895059],
       [0.3665561 , 0.19221963, 0.48049178, 0.09068976, 0.42766543],
       [0.55882314, 0.63648047, 0.14908652, 0.01125046, 0.31359345],
       [0.99776511, 0.32455296, 0.68490705, 0.3007646 , 0.98886055],
       [0.74762362, 0.20717111, 0.92857466, 0.89420305, 0.68361774]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [11]:
np.random.randint(20,50,size=(3,4))

array([[37, 24, 34, 37],
       [25, 41, 32, 47],
       [34, 46, 24, 33]])

#### 13. Reshape the array below with shape 6x8

In [12]:
ranarr=[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]

In [13]:
ranarr =np.array(ranarr)
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [14]:
np.array(ranarr).reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [15]:
#reshape with -1
np.array(ranarr).reshape(4,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [16]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [17]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [18]:
mat[:,0]

array([ 1,  5,  9, 13])

In [19]:
mat[:,[0]]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

#### 16. Get the values in 2nd row for every 2 step.

In [20]:
mat[1,[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [21]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
mat[:,2] =77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [23]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [24]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [25]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [26]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [27]:
arr2=np.array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [28]:
np.std(arr2)

29.700546274093877

#### 22. Get the sum of second column from array above

In [29]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [30]:
sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [31]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
mat[2]


array([ 9, 10, 11, 12])

In [33]:
#median
np.median(mat[2])

10.5

In [34]:
#mean
np.mean(mat[2])

10.5

In [35]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [4]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [5]:
sal=pd.read_csv('/content/drive/MyDrive/Salaries.csv', encoding="UTF-8")

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [8]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [9]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [10]:
sal=pd.DataFrame(sal)

In [11]:
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [12]:
#max
#sal.TotalPay.max()
max(sal.TotalPay)

567595.43

In [13]:
#avg
sal_avg=sal["TotalPay"].mean()
sal["TotalPay"].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [14]:
(sal.TotalPay>sal_avg).value_counts()

False    79165
True     69489
Name: TotalPay, dtype: int64

In [15]:
(sal.TotalPay>74768.321971703).value_counts()

False    79165
True     69489
Name: TotalPay, dtype: int64

**How much does ALBERT PARDINI make (including benefits)?**

In [16]:
sal["TotalPayBenefits"][2]   #İSTEDİĞİMİZ SÜTÜNDAKİ istediğimiz satır

335279.91

**Who is lowest paid person**

In [69]:
sal["EmployeeName"].iloc[sal.TotalPay.sort_values().head(1)]


148036    Carlos J Hernandez
Name: EmployeeName, dtype: object

In [76]:
[sal.TotalPay.sort_values(ascending=False).tail(1)]  

[148653   -618.13
 Name: TotalPay, dtype: float64]

In [89]:
#sal[(sal["EmployeeName"])][(sal(["TotalPay"]==-618.13))]

KeyError: ignored

**What are the unique Jobs in dataset?**

In [20]:
sal.JobTitle.sort_index().unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [54]:
sal.JobTitle.value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES       1
ASSISTANT DIRECTOR OF CLINICAL SERVICES II           1
Mobile Equipment Supervisor                          1
COURT CLERK                                          1
Name: JobTitle, Length: 2159, dtype: int64

In [55]:
sal.JobTitle.value_counts(ascending=True).head(3)

COURT CLERK                                   1
Mobile Equipment Supervisor                   1
ASSISTANT DIRECTOR OF CLINICAL SERVICES II    1
Name: JobTitle, dtype: int64

In [56]:
sal.JobTitle.value_counts().tail(3)

ASSISTANT DIRECTOR OF CLINICAL SERVICES II    1
Mobile Equipment Supervisor                   1
COURT CLERK                                   1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [30]:
sal["TotalPayBenefits"].mean()

93692.55481056834

In [57]:
sal.groupby(["Year"]).count()

Id  EmployeeName  JobTitle  ...  Notes  Agency  Status
Year                                 ...                       
2011  36159         36159     36159  ...      0   36159       0
2012  36766         36766     36766  ...      0   36766       0
2013  37606         37606     37606  ...      0   37606       0
2014  38123         38123     38123  ...      0   38123       0

[4 rows x 12 columns]

In [38]:
sal[(sal["Year"]==2012)&(sal["TotalPayBenefits"]>93692.55481056834)].count()

Id                  20366
EmployeeName        20366
JobTitle            20366
BasePay             20366
OvertimePay         20366
OtherPay            20366
Benefits            20366
TotalPay            20366
TotalPayBenefits    20366
Year                20366
Notes                   0
Agency              20366
Status                  0
dtype: int64

In [351]:
[sal["TotalPayBenefits"]>sal_avg]&()

[0         False
 1         False
 2         False
 3         False
 4         False
           ...  
 148649    False
 148650    False
 148651    False
 148652    False
 148653    False
 Name: TotalPayBenefits, Length: 148654, dtype: bool]

**How many people have the word Manager in their job title?**

In [47]:
#use apply function here
sal[sal["JobTitle"]=="Mobile Equipment Supervisor"]


Id   EmployeeName  ...         Agency  Status
57495  57496  Michael Handy  ...  San Francisco     NaN

[1 rows x 13 columns]

In [50]:
sal[sal["JobTitle"]=="GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY"]

Id    EmployeeName  ...         Agency  Status
0    1  NATHANIEL FORD  ...  San Francisco     NaN
83  84  EDWARD REISKIN  ...  San Francisco     NaN

[2 rows x 13 columns]

In [58]:
sal[sal["JobTitle"]=="*MANAGER*"].value_counts()

Series([], dtype: int64)

In [55]:
sal["JobTitle"].value_counts()

Transit Operator                   7036
Special Nurse                      4389
Registered Nurse                   3736
Public Svc Aide-Public Works       2518
Police Officer 3                   2421
                                   ... 
ASSISTANT RECREATION SUPERVISOR       1
MAYORAL STAFF II                      1
COURT SUPERVISOR I                    1
WAREHOUSE WORKER                      1
Asst Chf Prob Ofc, Juv Prob           1
Name: JobTitle, Length: 2159, dtype: int64

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [222]:
sal_new=sal.drop(["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"], axis=1)
#sal.drop(columns = ["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"])
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [326]:
sal_new=sal_new.iloc[:,1:]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [228]:
sal_new.describe()

Id       TotalPay  TotalPayBenefits
count  148654.000000  148654.000000     148654.000000
mean    74327.500000   74768.321972      93692.554811
std     42912.857795   50517.005274      62793.533483
min         1.000000    -618.130000       -618.130000
25%     37164.250000   36168.995000      44065.650000
50%     74327.500000   71426.610000      92404.090000
75%    111490.750000  105839.135000     132876.450000
max    148654.000000  567595.430000     567595.430000

In [332]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]

EmployeeName  ... TotalPayBenefits
15847   TATYANA ROTENBERG  ...         74764.87
15848         WINSTON HOM  ...         74761.55
15849        CRAIG RIGLER  ...         74759.92
15850           WENDY TAN  ...         74756.76
15851      KENNETH BREWER  ...         74751.59
...                   ...  ...              ...
148648        Leon Walker  ...             0.00
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00

[79164 rows x 4 columns]

In [331]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]["EmployeeName"]

15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object