<a href="https://colab.research.google.com/github/glcn35/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [5]:
data =np.random.randn(3,2)

In [6]:
data*10

array([[ 7.0787368 , -7.90004797],
       [ 1.01806472,  8.40443258],
       [-1.55531221, 14.02607596]])

In [7]:
data.shape

(3, 2)

In [8]:
data.dtype

dtype('float64')

In [9]:
liste =[3,6.5,0,1,9]

In [11]:
dizi= np.array(liste)
print(dizi)

[3.  6.5 0.  1.  9. ]


In [12]:
liste =[[1,2,3],[4,5,6]]

In [13]:
dizi= np.array(liste)
print(dizi)

[[1 2 3]
 [4 5 6]]


In [15]:
dizi=np.zeros(7)
print(dizi)

[0. 0. 0. 0. 0. 0. 0.]


In [16]:
dizi=np.ones(7)
print(dizi)

[1. 1. 1. 1. 1. 1. 1.]


In [18]:
dizi=np.ones((5,4))
print(dizi)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
dizi = np.array([1,2,3], dtype=int)

In [22]:
dizi.dtype

dtype('int64')

In [23]:
dizi2= dizi.astype(np.float64)

In [24]:
dizi2.dtype

dtype('float64')

In [27]:
dizi1 =np.array([1.2,3.5,7,8.9])

In [28]:
dizi1.dtype                      #floatı int çevirince virgülden sonrası gider

dtype('float64')

In [29]:
dizi2= dizi1.astype(np.int32)

In [30]:
dizi2

array([1, 3, 7, 8], dtype=int32)

In [31]:
dixi = np.array([[1,2,3],[4,5,6]])

In [32]:
dixi*dixi

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
dixi- dixi

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
1/dixi

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
dixi**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
dizi=np.arange(10)

In [39]:
dizi


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
dizi[7]                    #indexleme

7

In [41]:
dizi[3:8]

array([3, 4, 5, 6, 7])

In [42]:
dizi[3:8]=13             #dilimdeki her indexe 13 değerini atadık.bu özellik pythonda yoktu.numpy da var

In [43]:
dizi

array([ 0,  1,  2, 13, 13, 13, 13, 13,  8,  9])

çok boyutlu dizilerde index ve **sliceing** **kalın metin:**

In [45]:
dizi2b =np.array(([1,2,3],[4,5,6],[7,8,9]))

In [46]:
dizi2b[0]

array([1, 2, 3])

In [47]:
dizi2b[1][2]

6

In [48]:
dizi2b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
dizi2b[0,:2]

array([1, 2])

In [53]:
dizi2b[0][:2]

array([1, 2])

In [56]:
dizi2b[:2,1:]         #x ve y ekseni gibi ama 3. z yi nasıl alacağım????

array([[2, 3],
       [5, 6]])

In [58]:
dizi2b[:,:1]

array([[1],
       [4],
       [7]])

In [60]:
isimler= np.array(["ali","veli","ayşe","ali"])

In [61]:
veri=np.random.randn(4,3)

In [62]:
veri[isimler =="ali"]

array([[-1.24088877, -0.13231133, -0.44978855],
       [-0.66766112,  0.51186929, -0.55557004]])

In [63]:
veri[isimler =="ali", 1:]

array([[-0.13231133, -0.44978855],
       [ 0.51186929, -0.55557004]])

In [64]:
veri[~(isimler=="ali")]                   #~ ali dışındakiler anlamı katar.

array([[ 0.7037935 ,  0.03420729,  0.13772758],
       [-0.96405419, -0.59687692, -1.1173155 ]])

In [65]:
sec=(isimler== "ali")|(isimler=="ayşe")

In [66]:
veri[sec]

array([[-1.24088877, -0.13231133, -0.44978855],
       [-0.96405419, -0.59687692, -1.1173155 ],
       [-0.66766112,  0.51186929, -0.55557004]])

In [67]:
veri[veri<0] =0          #sıfırdan küçük verilerin yerine 0 atadık

In [68]:
veri

array([[0.        , 0.        , 0.        ],
       [0.7037935 , 0.03420729, 0.13772758],
       [0.        , 0.        , 0.        ],
       [0.        , 0.51186929, 0.        ]])

ARANGE

In [69]:
dizi= np.arange(12).reshape(3,4)

In [70]:
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
dizi.T #TRANSPOZ

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [72]:
np.dot(dizi.T, dizi)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [73]:
dizi.mean()

5.5

In [74]:
dizi.sum()

66

In [75]:
dizi.mean(1)         #satır ortalamaları için 1 sütun için 0 kullanılır

array([1.5, 5.5, 9.5])

In [76]:
dizi.mean(0)

array([4., 5., 6., 7.])

In [77]:
dizi.sort()

In [78]:
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
dizi.sort(1)
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
say=np.array([11,1,2,3,1,4,1])                 #unique tekrar edenleri alma

In [82]:
np.unique(say)

array([ 1,  2,  3,  4, 11])

In [83]:
dizi=np.arange(10)

In [85]:
np.save("bir_dizi_kaydetme", dizi)

In [86]:
np.load("bir_dizi_kaydetme.npy")   #kayıtlı diziyi yükleme

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.random.normal(size=(4,3))

array([[ 1.21809959, -2.4377233 , -0.52441116],
       [ 0.15316503,  0.78327808, -0.2690142 ],
       [-0.43391932,  0.59304741,  0.9178391 ],
       [-0.24194056,  2.27665944, -0.39348292]])