<a href="https://colab.research.google.com/github/glcn35/NUMPY/blob/main/numpy_concatenate_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np


Joining NumPy Arrays

**concatenate()** Birleştirme, iki veya daha fazla dizinin içeriğini tek bir diziye koymak anlamına gelir.

SQL'de tabloları bir anahtara göre birleştiririz, oysa NumPy'de dizileri eksenlere göre birleştiririz.

Fonksiyona birleştirmek istediğimiz bir dizi diziyi concatenate()eksen ile birlikte iletiyoruz. Eksen açıkça geçirilmezse 0 olarak alınır.

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [2]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**stack-**İstifleme, birleştirme ile aynıdır, tek fark istiflemenin yeni bir eksen boyunca yapılmasıdır.

İkinci eksen boyunca iki 1-B diziyi birleştirebiliriz, bu da onları üst üste koymaya neden olur, yani. istifleme.

stack()Eksen ile birlikte metoda dahil etmek istediğimiz bir dizi diziyi iletiyoruz. Eksen açıkça geçilmezse 0 olarak alınır.

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


hstack() satırlar boyunca yığın yapmak.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


vstack()  sütunlar boyunca yığın yapmak.

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


dstack() derinlikle aynı olan yükseklik boyunca yığın yapmak.

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

Bölme, Katılmanın ters işlemidir.

Birleştirme, birden çok diziyi tek bir dizide birleştirir ve Bölme, bir diziyi birden çok diziye böler.

Dizileri bölmek için kullanıyoruz array_split(), bölmek istediğimiz diziyi ve bölme sayısını iletiyoruz.


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)                       #split()ancak yukarıdaki örnekte olduğu gibi bölme için kaynak dizideki öğeler daha az olduğunda öğeleri ayarlamaz, array_split()düzgün çalışır ancak split()başarısız olu
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [13]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])   #2 boyutlu diziyi üç 2 boyutlu diziye ayırır
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
